theme: jekyll-theme-leap-day
title: [Python dasturlash tili]
description: [O'zbek tilida]
show_downloads: false
show_github_repository: false
show_description: true
is_theme_by: false
github:
  martianvenusian_url: https://martianvenusian.github.io
  repository_name: [Python dasturlash tili]
